import type { Metadata } from "next";
import {Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";
import {TheHeader} from "@/app/components/Header/TheHeader";
import {TheFooter} from "@/app/components/Footer/TheFooter";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
			<body className={`${inter.className} testCenter content`}>
				<TheHeader />
					<main className='main'>
						{children}
					</main>
				<TheFooter />
			</body>
    </html>
  );
}
